# Generated by Django 6.0 on 2026-01-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('FARMER', 'Farmer (seller)'), ('BUYER', 'Buyer'), ('ADMIN', 'Admin')], default='BUYER', max_length=10),
        ),
    ]
