# Generated by Django 6.0 on 2026-01-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_listing_image_url_listing_quantity_listing_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
