# Generated by Django 6.0 on 2026-01-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='evening_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='morning_session',
            field=models.BooleanField(default=False),
        ),
    ]
