# Generated by Django 5.2.10 on 2026-01-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GENERAL', 'General Notification'), ('WIN', 'Auction Win Celebration')], default='GENERAL', max_length=10),
        ),
    ]
