# Generated by Django 5.2.10 on 2026-01-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_listing_winner_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_used_free_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='membership_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
