# Generated by Django 5.2.10 on 2026-01-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_has_used_free_trial_user_membership_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='membership_type',
            field=models.CharField(blank=True, choices=[('TRIAL', 'Free Trial'), ('MONTHLY', 'Monthly Plan'), ('YEARLY', 'Yearly Plan')], default='TRIAL', max_length=10, null=True),
        ),
    ]
