# Generated by Django 5.2.10 on 2026-01-29 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Full address for delivery/pickup'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.FileField(blank=True, help_text='Upload ID proof for verification (Farmers only)', null=True, upload_to='id_proofs/'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('PICKUP', 'Pickup from Farm'), ('DELIVERY', 'Home Delivery')], default='PICKUP', max_length=10)),
                ('shipping_address', models.TextField(help_text='Address at time of order')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='accounts.listing')),
            ],
        ),
    ]
