# Generated by Django 5.2.10 on 2026-02-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_address_user_id_proof_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, help_text='Farm or Business Name', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='gstin',
            field=models.CharField(blank=True, help_text='GST Identification Number', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_number',
            field=models.CharField(blank=True, help_text='Permanent Account Number', max_length=10),
        ),
    ]
