# Generated by Django 5.2.10 on 2026-02-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_bank_account_number_user_bank_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Final calculated amount (Bid x Quantity)', max_digits=12),
        ),
    ]
